version: "3.9"
services:
  frontend:
    stdin_open: true
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - '80:80' 
  backend:
    container_name: backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.prod
    restart: always
    env_file: .env
    ports:
        - "${BACKEND_PORT}:${BACKEND_PORT}"