name: Deploy Monorepo
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Build and Export Next.js App
      run: |
        cd packages/frontend
        npm install
        npm run build
        npm run export
    - name: Build and Transpile Nest.js App
      run: |
        cd packages/backend
        npm install
        npm run build
    - name: Package Applications
      run: |
        cd ../..
        zip -r deploy.zip packages/frontend/.next packages/backend/dist
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ebs-deploy
        environment_name: Ebddeploy-env
        package: deploy.zip
        region: us-west-2